org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.1.2
yarn_mappings=26.1.2+build.1
loader_version=0.18.4
fabric_version=0.155.2+26.1.2
plasmo_voice_api_version=2.1.13
openpnp_capture_version=0.0.28-0

target_java_version=25
mod_version=0.1.0-SNAPSHOT
maven_group=dev.nikita.tgvoice
archives_base_name=plasmo-telegram-voice
